### ISSUE TITLE
GenericTypeReflector.getExactSuperType fails for static nested (or anonymous) classes 

### ISSUE THREAD

**Issue by ePaul** [coekie/gentyref#4]
**Context**
Assume we have an outer class or interface `A<X>` with type parameters, and a static class `B` nested in there, which implements this or another generic class/interface `C<Y>` with a concrete type parameter (e.g. `B implements C<String>`).

```java
class A<X> {
    static class B implements C<String> {
    }
}
interface C<Y> {}
```

**Wrong behavior**
Then `GenericTypeReflector.getExactSuperType(B.class, C.class)` returns the raw type `C`

**Expected behavior**
`GenericTypeReflector.getExactSuperType(B.class, C.class)` should return the parameterized Type `C<String>`.

**Analysis**
In `GenericTypeReflector.isMissingTypeParameters` (which tries to find out whether we have a (partially) raw type at hand), the loop goes through enclosing classes even if the class itself is static, and thus the type parameters of the enclosing class have no effect on the nested class. It should stop for static nested classes.

**Workaround**
Put your static nested class into an outer class without type parameters, or make it a top-level class itself.

**Comment by kaqqao** [comment]
@ePaul I realize this issue is 3 years old now, but for what it's worth, I maintain [a fork of this project](https://github.com/leangen/geantyref) where this is fixed.

**Comment by coekie** [comment]
Thanks @kaqqao. 
Yes, use the fork. I'm going to archive this repository.
